// Builds src/data/answers.ts (answers grouped by difficulty tier) and
// src/data/guesses.ts (every acceptable guess) from the raw lists in
// scripts/data/. Run with `yarn words` after changing any input list.
//
// zipf.tsv holds wordfreq Zipf frequencies for answers.txt; regenerate it with
// Python's `wordfreq` package if answers.txt changes (see README).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const dataDir = `${root}scripts/data/`;

const readList = (name: string): string[] =>
  readFileSync(dataDir + name, "utf8")
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => /^[a-z]{5}$/.test(line));

// Too obscure to be a fair answer at any tier (e.g. "gayly", "wooer"), but
// still accepted as guesses.
const MIN_ZIPF = 1.8;

const TIERS = ["easy", "medium", "hard", "brutal"] as const;
// Percentile cut-offs on the combined difficulty score.
const TIER_CUTOFFS = [0.4, 0.7, 0.9, 1];

const blocked = new Set(readList("blocklist.txt"));
const excluded = new Set(readList("answer-exclude.txt"));
const zipf = new Map(
  readFileSync(dataDir + "zipf.tsv", "utf8")
    .trim()
    .split("\n")
    .map((line) => {
      const [word, freq] = line.split("\t");
      return [word, Number(freq)] as const;
    }),
);

const rawAnswers = [...new Set(readList("answers.txt"))];
const answers = rawAnswers.filter(
  (w) => !blocked.has(w) && !excluded.has(w) && (zipf.get(w) ?? 0) >= MIN_ZIPF,
);
const guesses = [...new Set([...rawAnswers, ...readList("allowed.txt")])]
  .filter((w) => !blocked.has(w))
  .sort();

const letterFreq = new Map<string, number>();
const positionFreq = Array.from({ length: 5 }, () => new Map<string, number>());
for (const word of answers) {
  for (const letter of new Set(word)) {
    letterFreq.set(letter, (letterFreq.get(letter) ?? 0) + 1);
  }
  [...word].forEach((letter, i) =>
    positionFreq[i].set(letter, (positionFreq[i].get(letter) ?? 0) + 1),
  );
}

// Words one letter apart from many other answers ("_IGHT", "_OUND") are the
// classic Wordle trap: you can know four letters and still burn every guess.
const neighbourCount = (word: string): number =>
  answers.filter(
    (other) =>
      other !== word && [...word].filter((c, i) => c !== other[i]).length === 1,
  ).length;

const commonality = (word: string): number =>
  [...new Set(word)].reduce((sum, c) => sum + (letterFreq.get(c) ?? 0), 0) +
  [...word].reduce((sum, c, i) => sum + (positionFreq[i].get(c) ?? 0), 0);

const repeats = (word: string): number => 5 - new Set(word).size;

// Maps each word's raw metric to its 0–1 percentile rank so metrics with
// different scales can be weighted together.
function percentiles(values: number[]): number[] {
  const sorted = [...values].sort((a, b) => a - b);
  return values.map((v) => sorted.indexOf(v) / (sorted.length - 1));
}

const neighbourPct = percentiles(answers.map(neighbourCount));
const commonalityPct = percentiles(answers.map(commonality));
const repeatsPct = percentiles(answers.map(repeats));
const zipfPct = percentiles(answers.map((w) => zipf.get(w) ?? 0));

const scored = answers
  .map((word, i) => ({
    word,
    score:
      0.35 * neighbourPct[i] +
      0.2 * (1 - commonalityPct[i]) +
      0.15 * repeatsPct[i] +
      0.3 * (1 - zipfPct[i]),
  }))
  .sort((a, b) => a.score - b.score);

const tiers: Record<(typeof TIERS)[number], string[]> = {
  easy: [],
  medium: [],
  hard: [],
  brutal: [],
};
scored.forEach(({ word }, i) => {
  const pct = (i + 1) / scored.length;
  const tier = TIERS[TIER_CUTOFFS.findIndex((cut) => pct <= cut)];
  tiers[tier].push(word);
});

const formatList = (words: string[]): string =>
  words
    .toSorted()
    .map((w) => `    "${w}",`)
    .join("\n");

const header =
  "// Generated by scripts/build-words.ts — do not edit by hand.\n\n";

writeFileSync(
  `${root}src/data/answers.ts`,
  header +
    `import type { Tier } from "../types";\n\n` +
    `export const ANSWERS: Readonly<Record<Tier, readonly string[]>> = {\n` +
    TIERS.map((t) => `  ${t}: [\n${formatList(tiers[t])}\n  ],`).join("\n") +
    `\n};\n`,
);

writeFileSync(
  `${root}src/data/guesses.ts`,
  header +
    `export const GUESSES: ReadonlySet<string> = new Set(\n` +
    `  ${JSON.stringify(guesses.join(" "))}.split(" "),\n);\n`,
);

console.log(
  `${answers.length} answers (${TIERS.map((t) => `${t} ${tiers[t].length}`).join(", ")}); ${guesses.length} guesses`,
);
for (const t of TIERS) {
  const step = Math.floor(tiers[t].length / 12);
  const sample = tiers[t].filter((_, i) => i % step === 0).slice(0, 12);
  console.log(`  ${t}: ${sample.join(" ")}`);
}
