// Fetches Wiktionary definitions for answers WordNet doesn't cover and writes
// scripts/data/definitions-wiktionary.tsv, which build-definitions.ts reads.
// Run with `yarn definitions:fetch` after the answer list changes; it's the
// only step that needs the network, so `yarn words` stays offline.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { answers, readTsv, wordnetDefinitions } from "./build-definitions.ts";

const root = fileURLToPath(new URL("..", import.meta.url));
// Wikimedia's API policy asks for an identifying User-Agent.
const HEADERS = {
  "User-Agent": "fivefold-definitions (https://github.com/craigmcn/fivefold)",
};

interface WiktionaryEntry {
  partOfSpeech: string;
  definitions: { definition: string }[];
}

const NAMED_ENTITIES: Record<string, string> = {
  amp: "&",
  apos: "'",
  gt: ">",
  lt: "<",
  mdash: "—",
  nbsp: " ",
  ndash: "–",
  quot: '"',
};

// Unknown named entities are kept as text: a stray "&foo;" is easy to spot in
// the TSV, whereas dropping it would silently corrupt the definition.
export function decodeEntities(text: string): string {
  return text.replace(
    /&(#x[\da-f]+|#\d+|[a-z]+);/gi,
    (entity, body: string) => {
      if (body[0] === "#") {
        const hex = body[1] === "x" || body[1] === "X";
        return String.fromCodePoint(
          parseInt(body.slice(hex ? 2 : 1), hex ? 16 : 10),
        );
      }
      return NAMED_ENTITIES[body.toLowerCase()] ?? entity;
    },
  );
}

// The REST definitions are HTML fragments; some carry inline style blocks.
export function plainText(html: string): string {
  return decodeEntities(
    html
      .replace(/<style[\s\S]*?<\/style>/g, "")
      .replace(/<[^>]+>/g, "")
      .replace(/\.mw-parser-output[^}]*\}/g, ""),
  )
    .split("\n")[0]
    .trim();
}

async function firstDefinition(word: string): Promise<string | null> {
  const response = await fetch(
    `https://en.wiktionary.org/api/rest_v1/page/definition/${word}`,
    { headers: HEADERS },
  );
  if (!response.ok) return null;
  const data = (await response.json()) as { en?: WiktionaryEntry[] };
  for (const entry of data.en ?? []) {
    for (const { definition } of entry.definitions) {
      const text = plainText(definition);
      if (text) return text;
    }
  }
  return null;
}

// Guarded so tests can import the helpers without fetching or rewriting the
// TSV.
async function main(): Promise<void> {
  const wordnet = wordnetDefinitions();
  const overrides = readTsv("definition-overrides.tsv");
  const gaps = answers.filter((w) => !wordnet.has(w) && !overrides.has(w));
  const lines = [
    "# Wiktionary (https://en.wiktionary.org), CC BY-SA 4.0. First English",
    "# sense only. Generated by scripts/fetch-wiktionary.ts.",
  ];
  for (const word of gaps) {
    const definition = await firstDefinition(word);
    if (definition) lines.push(`${word}\t${definition}`);
    else console.warn(`No Wiktionary definition for ${word}`);
    // Stay well under Wikimedia's rate limits.
    await new Promise((resolve) => setTimeout(resolve, 200));
  }
  writeFileSync(
    `${root}scripts/data/definitions-wiktionary.tsv`,
    `${lines.join("\n")}\n`,
  );
  console.log(`${lines.length - 2}/${gaps.length} gaps filled from Wiktionary`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) await main();
