// Fetches Wiktionary definitions for answers WordNet doesn't cover and writes
// scripts/data/definitions-wiktionary.tsv, which build-definitions.ts reads.
// Run with `yarn definitions:fetch` after the answer list changes; it's the
// only step that needs the network, so `yarn words` stays offline.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { answers, readTsv, wordnetDefinitions } from "./build-definitions.ts";

const root = fileURLToPath(new URL("..", import.meta.url));
// Wikimedia's API policy asks for an identifying User-Agent.
const HEADERS = {
  "User-Agent": "fivefold-definitions (https://github.com/craigmcn/fivefold)",
};

interface WiktionaryEntry {
  partOfSpeech: string;
  definitions: { definition: string }[];
}

// The REST definitions are HTML fragments; some carry inline style blocks.
function plainText(html: string): string {
  return html
    .replace(/<style[\s\S]*?<\/style>/g, "")
    .replace(/<[^>]+>/g, "")
    .replace(/\.mw-parser-output[^}]*\}/g, "")
    .replace(/&#?\w+;/g, (entity) =>
      entity === "&amp;" ? "&" : entity === "&nbsp;" ? " " : "",
    )
    .split("\n")[0]
    .trim();
}

async function firstDefinition(word: string): Promise<string | null> {
  const response = await fetch(
    `https://en.wiktionary.org/api/rest_v1/page/definition/${word}`,
    { headers: HEADERS },
  );
  if (!response.ok) return null;
  const data = (await response.json()) as { en?: WiktionaryEntry[] };
  for (const entry of data.en ?? []) {
    for (const { definition } of entry.definitions) {
      const text = plainText(definition);
      if (text) return text;
    }
  }
  return null;
}

const wordnet = wordnetDefinitions();
const overrides = readTsv("definition-overrides.tsv");
const gaps = answers.filter((w) => !wordnet.has(w) && !overrides.has(w));
const lines = [
  "# Wiktionary (https://en.wiktionary.org), CC BY-SA 4.0. First English",
  "# sense only. Generated by scripts/fetch-wiktionary.ts.",
];
for (const word of gaps) {
  const definition = await firstDefinition(word);
  if (definition) lines.push(`${word}\t${definition}`);
  else console.warn(`No Wiktionary definition for ${word}`);
  // Stay well under Wikimedia's rate limits.
  await new Promise((resolve) => setTimeout(resolve, 200));
}
writeFileSync(
  `${root}scripts/data/definitions-wiktionary.tsv`,
  `${lines.join("\n")}\n`,
);
console.log(`${lines.length - 2}/${gaps.length} gaps filled from Wiktionary`);
